apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: bla
spec:
  serviceAccountName: build-bot 
  source:
    git:
      url: https://github.com/k15r/knative-node.git
      revision: master
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    args:
    - --dockerfile=/workspace/Dockerfile
    - --destination=k15r/knative-node
    volumeMounts:
    - name: bla-deps
      mountPath: /src
  volumes:
  - name: bla-deps
    configMap:
      defaultMode: 420
      name: bla-knative
