 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: build-bot
 secrets:
 - name: basic-user-pass
---

apiVersion: v1
data:
  handler: handler.main
  handler.js: |-
    module.exports = { main: function (event, context) {
    return "blaa"
    } }
  package.json: |-
    {
          "name": "app",
          "version": "0.0.1",
          "dependencies": {
            "redis":  "2.8.0",
            "double-ended-queue": "2.1.0-0",
            "redis-commands": "1.3.1",
            "redis-parser": "2.6.0"
          }
    }
kind: ConfigMap
metadata:
  labels:
    created-by: kubeless
    function: bla
  name: bla-knative
---

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-nodejs
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: build-bot 
        source:
          git:
            url: https://github.com/k15r/knative-node.git
            revision: master
        steps:
        - name: build-and-push
          image: gcr.io/kaniko-project/executor
          args:
          - --dockerfile=/workspace/Dockerfile
          - --destination=k15r/knative-node
          volumeMounts:
          - name: bla-deps
            mountPath: /src
        volumes:
        - name: bla-deps
          configMap:
            defaultMode: 420
            name: bla-knative
      revisionTemplate:
        spec:
          container:
            image: k15r/knative-node
            env:
            - name: FUNC_HANDLER
              value: main
            - name: MOD_NAME
              value: handler
            - name: FUNC_TIMEOUT
              value: "180"
            - name: FUNC_RUNTIME
              value: nodejs8
            - name: FUNC_MEMORY_LIMIT
              value: 128Mi
            - name: FUNC_PORT
              value: "8080"
            - name: KUBELESS_INSTALL_VOLUME
              value: /kubeless
            - name: NODE_PATH
              value: $(KUBELESS_INSTALL_VOLUME)/node_modules